### ISSUE TITLE
Continuously receiving error on Member

### ISSUE THREAD

**Issue by toofun666** [frappe/non_profit#10]
Whenever we enter the details of a Member, we receive the error:

### App Versions
```
{
	"erpnext": "13.34.0",
	"frappe": "13.33.0",
	"iflliler": "0.0.1"
}
```
### Route
```
Form/Member/NPO-MEM-2022-00001
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1448, in call
    return fn(*args, **newargs)
TypeError: get_last_membership() missing 1 required positional argument: 'member'

```
### Request Data
```
{
	"type": "POST",
	"args": {},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.get_last_membership"
}
```
### Response Data
```
{
	"exception": "TypeError: get_last_membership() missing 1 required positional argument: 'member'"
}
```

**Comment by dasistwas** [comment]
HI @toofun666 I published a fix for erpnext v13.
https://github.com/frappe/non_profit/issues/18
