### ISSUE TITLE
ImportError: Module import failed for Membership, the DocType you're trying to open might be deleted.<br> Error: No module named 'payments'

### ISSUE THREAD

**Issue by Ahraar1** [frappe/non_profit#39]
I created a new site and encountered this problem during installation :

`Installing non_profit...
Updating DocTypes for non_profit    : [=============                           ] 33%An error occurred while installing non_profit: Module import failed for Membership, the DocType you're trying to open might be deleted.<br> Error: No module named 'payments'
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 255, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/non_profit/non_profit/non_profit/doctype/membership/membership.py", line 14, in <module>
    from non_profit.non_profit.doctype.member.member import create_member
  File "apps/non_profit/non_profit/non_profit/doctype/member/member.py", line 11, in <module>
    from payments.utils import get_payment_gateway_controller
ModuleNotFoundError: No module named 'payments'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 400, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 295, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 241, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 292, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1098, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 931, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1283, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1265, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 928, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 410, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 508, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 259, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Membership, the DocType you're trying to open might be deleted.<br> Error: No module named 'payments'`

**Comment by Ahraar1** [comment]
Requirement for non_profit App :
$ bench get-app payments
